
name: Auto merge into the master branch
on:
  pull_request:
    types:
      - opened
    branches:
      - {{secrets.BRANCH_NAME }}
  workflow_dispatch:
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
        - id: automerge
          name: automerge
          uses: "pascalgn/automerge-action@v0.15.5"
          env:
            GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
            MERGE_METHOD: "merge"
